name: Build VTosters Lite

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
          add-to-path: true

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Download tools
        run: |
          sudo apt update
          sudo apt install -y default-jre python3 zipalign
          chmod +x scripts/apktool.jar
          chmod +x scripts/apksigner.jar
          rustup target add armv7-linux-androideabi
          rustup target add aarch64-linux-android

      - name: Fix Gradle version
        run: |
          mkdir -p gradle/wrapper
          echo "distributionUrl=https\\://services.gradle.org/distributions/gradle-7.6-all.zip" > gradle/wrapper/gradle-wrapper.properties

      - name: Build VTLite
        run: |
          ./gradlew generateBuildTasks
          ./gradlew prepareDevKitgerGedev
          java -jar scripts/apktool.jar b small -o small/VTLite.apk --use-aapt2 -p s
          zipalign -p -f 4 small/VTLite.apk small/VTLite.apk_aligned
          mv small/VTLite.apk_aligned small/VTLite.apk
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Sign and verify the apk
        run: |
          java -jar scripts/apksigner.jar sign --ks scripts/debug.keystore --ks-key-alias debug --ks-pass pass:android --key-pass pass:android small/VTLite.apk
          java -jar scripts/apksigner.jar verify small/VTLite.apk

      - name: Upload apk to artifact
        uses: actions/upload-artifact@v4
        with:
          name: VTLite.apk
          path: small/VTLite.apk
